version: '3'
services:
  lfb-rt-simulator:
    build: lfb-rt-simulator
    environment:
      - CSV_FILE_LOCATION=data/LFB_Incident_data_from_January_2017.csv.gz
      - PRODUCER_MAX_SLEEP_TIME_SECONDS=2
    expose:
        - "5678"
        - "5679"
    healthcheck:
      test: ["CMD-SHELL", "python3 src/healthcheck.py"]
      interval: 5s
      timeout: 10s
      retries: 5
    entrypoint: ["python3", "src/lfb_ws_server.py"]

  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=metapack
      - POSTGRES_PASSWORD=metapack
      - POSTGRES_DB=lfb
    logging:
      options:
        max-size: 10m
        max-file: "3"
    expose:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d lfb -U metapack"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./sql-consumer/src/sql/lfb-incidents-ddl.sql:/docker-entrypoint-initdb.d/lfb-incidents-ddl.sql

  sql-consumer:
    build: sql-consumer
    environment:
      - LFB_RT_SIMULATOR_URI=ws://lfb-rt-simulator:5678
      - POSTGRES_URI=postgresql://metapack:metapack@postgres/lfb
      - POSTGRES_HOSTNAME=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=metapack
      - POSTGRES_PASSWORD=metapack
      - POSTGRES_DB=lfb
    depends_on:
      lfb-rt-simulator:
        condition: service_healthy
      postgres:
        condition: service_healthy
    entrypoint: ["python3", "src/consumer_sync.py"]
